<a href="https://colab.research.google.com/github/JaeSang76/Data-Analysis/blob/main/%ED%96%89%EB%A0%AC%EA%B3%BC%EB%B0%B1%ED%84%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

# 스칼라 (0차원센터) : 하나의 숫자
s = np.array(18.2)
print(f"\n np.array(18.2) 스칼라 차원 : {s.ndim}, 모양 : {s.shape}")

# 벡터(1차원 텐서) : 숫자가 한 줄로 나열된 형
v = np.array([92.0, 85.5, 78.2])
print(f"\n v = np.array([92.0, 85.5, 78.2]) : {v}")
print(f"\n 인스턴스 v의 몇차원 텐서 v.ndim: {v.ndim}")
print(f"\n 인스턴스 v의 벡터 차원 v.shape: {v.shape}")
print(f"\n 인스턴스 v의 평균벡터 v.mean(): {v.mean()}")
print(f"\n 인스턴스 v의 모분산 v.var(): {v.var()}")

# 벡터(2차원 텐서) : 행과 열로 구성된 표 형태
m = np.array([[90,80], [75,88]]) # 2X2행렬  [90, 80]
                                  #         [75, 88]
print(f"\n m = np.array([90,80], [75, 88]) : {m}")
print(f"\n 인스턴스 m의 몇차원 텐서 v.ndim: {m.ndim}")
print(f"\n 인스턴스 m의 벡터 차원 v.shape: {m.shape}")
print(f"\n 인스턴스 m의 평균벡터 v.mean(): {m.mean()}")
print(f"\n 인스턴스 m의 모분산 v.var(): {m.var()}")



 np.array(18.2) 스칼라 차원 : 0, 모양 : ()

 v = np.array([92.0, 85.5, 78.2]) : [92.  85.5 78.2]

 인스턴스 v의 몇차원 텐서 v.ndim: 1

 인스턴스 v의 벡터 차원 v.shape: (3,)

 인스턴스 v의 평균벡터 v.mean(): 85.23333333333333

 인스턴스 v의 모분산 v.var(): 31.775555555555542

 m = np.array([90,80], [75, 88]) : [[90 80]
 [75 88]]

 인스턴스 m의 몇차원 텐서 v.ndim: 2

 인스턴스 m의 벡터 차원 v.shape: (2, 2)

 인스턴스 m의 평균벡터 v.mean(): 83.25

 인스턴스 m의 모분산 v.var(): 36.6875


In [11]:
import pandas as pd
import numpy as np

# 1. 기초 데이터(3명의 학생의 2개 과목 점수)
np_matrix = np.array([
                        [90, 80],
                        [75, 88],
                        [92, 95]
                    ])

# 2. NumPy 배열을 Pandas DataFrame형식으로 변환
df = pd.DataFrame(np_matrix,
                  columns = ['통계학', 'P/G'],
                  index = ['A', 'B', 'C'] )
print(f"\n NumPy 배열을 Pandas DataFrame형식으로 변환: \n {df}")
print(f"\n NumPy 배열의 값 : \n {df.values}")


 NumPy 배열을 Pandas DataFrame형식으로 변환: 
    통계학  P/G
A   90   80
B   75   88
C   92   95

 NumPy 배열의 값 : 
 [[90 80]
 [75 88]
 [92 95]]


In [15]:
# 벡터와 행렬의 연산
import numpy as np

A = np.array([[1,2], [3,4]])
B = np.array([[1,1], [0,1]])

# 덧셈, 뺄셈 및 스칼라배
print(f"행렬의 덧셈/뺄셈 : A+B \n {A+B}")
print(f"행렬의 스칼라배 : 3 * A \n {3 * A}")

행렬의 덧셈/뺄셈 : A+B 
 [[2 3]
 [3 5]]
행렬의 스칼라배 : 3 * A 
 [[ 3  6]
 [ 9 12]]


In [17]:
# 벡터와 행렬의 연산
import numpy as np

v1 = np.array([1,2])
v2 = np.array([4,6])

# 벡터의 내적(dot product)
dot_res = np.dot(v1, v2)
print(f"벡터의 내적 : np.dot(v1, v2) \n {dot_res}")
print(f"벡터의 내적 : v1.T @ v2 \n {v1.T @ v2}")
print(f"벡터의 내적 : v1 @ v2 \n {v1 @ v2}")

벡터의 내적 : np.dot(v1, v2) 
 16
벡터의 내적 : v1.T @ v2 
 16
벡터의 내적 : v1 @ v2 
 16


In [19]:
# 벡터와 행렬의 연산
import numpy as np

A = np.array([[1,2], [3,4]])
B = np.array([[1,1], [0,1]])

# 행렬의 곱(matrix multiplication)
matmul_res = np.matmul(A, B)
print(f"행렬의 곱 : np.matmul(A, B) \n {matmul_res}")
print(f"행렬의 곱 : A @ B \n {A @ B}")
print(f"원소별 곲 : A * B \n {A * B}")

행렬의 곱 : np.matmul(A, B) 
 [[1 3]
 [3 7]]
행렬의 곱 : A @ B 
 [[1 3]
 [3 7]]
원소별 곲 : A * B 
 [[1 2]
 [0 4]]


In [21]:
# 벡터와 행렬의 구조 변화
import numpy as np

# 4개의 원소를 가진 1차원 벡터를 2X2 행렬로 변환
v1 = np.array([92.0, 85.5, 78.2, 10.0])
mat_2X2 = v1.reshape(2,2) # v1.reshape(-1,2)으로도 가능

print(f"2X2 행렬로 변환 : v1.reshape(2,2) \n {mat_2X2}")
print(f"2X2 행렬로 변환 : v1.reshape(-1,2) \n {v1.reshape(-1,2)}")
print(f"2X2 행렬로 변환 : mat_2X2.shape \n {mat_2X2.shape}")

# 4개의 원소를 가진 1차원 벡터를 열벡터로 변환
mat_4X1 = v1.reshape(4, 1) # v1.reshape(-1,1)으로도 가능

print(f"4X1 행렬로 변환 : v1.reshape(4, 1) \n {mat_4X1}")
print(f"4X1 행렬로 변환 : mat_4X1.shape \n {mat_4X1.shape}")

print(f"1x4 행렬로 전치변환 : mat_4X1.T \n {mat_4X1.T}")
print(f"1x4 행렬로 전치변환 : mat_4X1.T \n {mat_4X1.T.shape}")


2X2 행렬로 변환 : v1.reshape(2,2) 
 [[92.  85.5]
 [78.2 10. ]]
2X2 행렬로 변환 : v1.reshape(-1,2) 
 [[92.  85.5]
 [78.2 10. ]]
2X2 행렬로 변환 : mat_2X2.shape 
 (2, 2)
4X1 행렬로 변환 : v1.reshape(4, 1) 
 [[92. ]
 [85.5]
 [78.2]
 [10. ]]
4X1 행렬로 변환 : mat_4X1.shape 
 (4, 1)
1x4 행렬로 전치변환 : mat_4X1.T 
 [[92.  85.5 78.2 10. ]]
1x4 행렬로 전치변환 : mat_4X1.T 
 (1, 4)


In [22]:
# 벡터와 행렬의 연산
import numpy as np

A = np.array([[1,2], [3,4]])
B = np.array([[1,1], [0,1]])

# 전치
print(f"행렬의 전치 : A.T \n {A.T}")

#역행렬
inv_res = np.linalg.inv(B)
print(f"행렬의 B의 역행렬 : np.linalg.inv(B) \n {inv_res}")
print(f"역행렬의 증명 : B @ B의 역행렬 \n {B @ inv_res}")

#역행렬를 구할수 없는 경우 : ad-bc = 0, 행렬식이 0인경우
## 따라서 역행렬을 구하려고 할때에는 행렬식이 0인 경우를 validation 체크 해야

행렬의 전치 : A.T 
 [[1 3]
 [2 4]]
행렬의 B의 역행렬 : np.linalg.inv(B) 
 [[ 1. -1.]
 [ 0.  1.]]
역행렬의 증명 : B @ B의 역행렬 
 [[1. 0.]
 [0. 1.]]
